### ISSUE TITLE
can't convert RuntimeError into String

### ISSUE THREAD

**Issue by hydra1983** [atoulme/Antwrap#3]
```
can't convert RuntimeError into String
d:/usr/share/ruby/lib/ruby/gems/1.9.1/gems/atoulme-Antwrap-0.7.2/lib/ant_project.rb:120:in `+'
d:/usr/share/ruby/lib/ruby/gems/1.9.1/gems/atoulme-Antwrap-0.7.2/lib/ant_project.rb:120:in `rescue in method_missing'
d:/usr/share/ruby/lib/ruby/gems/1.9.1/gems/atoulme-Antwrap-0.7.2/lib/ant_project.rb:124:in `method_missing'
```

**Comment by olleolleolle** [comment]
Fixed in https://github.com/atoulme/Antwrap/pull/4

**Comment by olleolleolle** [comment]
@atoulme This is repaired, and can be closed. ✨

**Comment by atoulme** [comment]
Thank you!
